#!/bin/bash
set -e

# Parse arguments
UI_MODE=false
CLI_MODE=false
POSITIONAL_ARGS=()
for arg in "$@"; do
  case "$arg" in
    --ui) UI_MODE=true ;;
    --cli) CLI_MODE=true ;;
    *) POSITIONAL_ARGS+=("$arg") ;;
  esac
done

if [ ${#POSITIONAL_ARGS[@]} -eq 0 ]; then
  echo "Usage: newf <ProjectName> [--ui|--cli]"
  echo "Examples:"
  echo "  newf MyAwesomeApp             # F# backend with Oxpecker"
  echo "  newf MyAwesomeApp --ui        # Elmish Land web frontend"
  echo "  newf MyAwesomeApp --cli       # Plain F# console/CLI project"
  exit 1
fi

PROJECT_NAME="${POSITIONAL_ARGS[0]}"
WORKSPACE_ROOT="$PWD"

# ── Helper: add new project to the root .slnx so Ionide picks it up ─────────
add_to_root_slnx() {
  local FSPROJ_PATH="$1"
  local SLNX
  SLNX=$(find "$WORKSPACE_ROOT" -maxdepth 1 -name "*.slnx" | head -1)
  if [ -z "$SLNX" ]; then
    echo "⚠️  No .slnx found in $WORKSPACE_ROOT — skipping solution update."
    return
  fi
  if grep -qF "$FSPROJ_PATH" "$SLNX"; then
    return
  fi
  sed -i "s|</Solution>|  <Project Path=\"$FSPROJ_PATH\" />\n</Solution>|" "$SLNX"
  echo "   Added to $(basename "$SLNX"): $FSPROJ_PATH"
}

# ── Helper: format newly generated F# source with Fantomas ──────────────────
# The repo root Directory.Build.props (WarningsAsErrors=FS0025, Nullable=enable,
# TreatWarningsAsErrors on Release) is picked up automatically by MSBuild for
# every project nested under $WORKSPACE_ROOT, so no per-project edits are
# needed for that. Formatting still needs to be applied explicitly though.
format_new_project() {
  local PROJECT_DIR="$1"
  (cd "$WORKSPACE_ROOT" && dotnet tool restore >/dev/null 2>&1; dotnet fantomas "$PROJECT_DIR") || \
    echo "⚠️  Fantomas formatting failed — run 'dotnet fantomas $PROJECT_DIR' manually."
}

# ── UI mode: scaffold an Elmish Land frontend ────────────────────────────────
if [ "$UI_MODE" = true ]; then
  echo "🚀 Creating new Elmish Land frontend: $PROJECT_NAME"

  mkdir -p "$PROJECT_NAME"
  cd "$PROJECT_NAME"

  # 1. Create a local tool manifest inside the project folder, then install elmish-land
  dotnet new tool-manifest
  dotnet tool install elmish-land

  # 2. Create .gitignore for the UI project
  cat > .gitignore << 'EOF'
# Node
node_modules/
npm-debug.log*

# Fable / Elmish Land
.fable/

# Vite build output
dist/

# .NET build artifacts
obj/
bin/

# OS
.DS_Store
Thumbs.db
EOF

  # 3. Init the project — pipe Enter to accept the default (hash routing)
  echo "" | dotnet elmish-land init

  # 3. Install Node dependencies generated by the init scaffolding
  npm install

  echo ""
  echo "✅ Elmish Land project '$PROJECT_NAME' created successfully!"
  echo ""
  echo "   Next steps:"
  echo "     cd $PROJECT_NAME"
  echo "     # Start dev server:  dotnet elmish-land server  (or: npm start)"
  echo "     # Build:             dotnet elmish-land build   (or: npm run build)"
  echo "     # Add a page:        dotnet elmish-land add page <PageName>"
  echo ""
  echo "Ionide + Elmish Land + Feliz + React are ready. Happy F# coding! 🎉"
  format_new_project "$PROJECT_NAME"
  add_to_root_slnx "$PROJECT_NAME/$PROJECT_NAME.fsproj"
  exit 0
fi

# ── CLI mode: scaffold a plain F# console/CLI project ───────────────────────
if [ "$CLI_MODE" = true ]; then
  echo "🚀 Creating new F# CLI project: $PROJECT_NAME"

  mkdir -p "$PROJECT_NAME"
  cd "$PROJECT_NAME"

  # 1. Create a plain F# console application
  dotnet new console -lang F# --force

  # 2. Suppress NU1510 warning (paket emits explicit PackageReferences for transitive deps)
  FSPROJ=$(ls *.fsproj)
  sed -i 's|<TargetFramework>|\n    <NoWarn>$(NoWarn);NU1510</NoWarn>\n    <TargetFramework>|' "$FSPROJ"

  # 3. Create a minimal paket.dependencies (no packages yet; add as needed)
  cat > paket.dependencies << 'EOF'
source https://api.nuget.org/v3/index.json
source /usr/share/dotnet/sdk/$(dotnet --version)/FSharp/library-packs

storage: none

nuget FSharp.Core
EOF

  # 4. Create paket.references with FSharp.Core (required because paket disables the implicit SDK reference)
  cat > paket.references << 'EOF'
FSharp.Core
EOF

  # 5. Wire up paket
  paket install

  # 6. Create a Fun.Build script
  cat > build.fsx << 'EOF'
#r "nuget: Fun.Build"

open Fun.Build

pipeline "Build" {
    stage "Clean" {
        run "dotnet clean"
    }
    stage "Restore" {
        run "dotnet restore"
    }
    stage "Build" {
        run "dotnet build"
    }
    runIfOnlySpecified false
}

pipeline "Run" {
    stage "Run" {
        run "dotnet run"
    }
    runIfOnlySpecified true
}

pipeline "Watch" {
    stage "Watch" {
        run "dotnet watch run"
    }
    runIfOnlySpecified true
}

tryPrintPipelineCommandHelp ()
EOF

  echo ""
  echo "✅ CLI project '$PROJECT_NAME' created successfully!"
  echo ""
  echo "   Next steps:"
  echo "     cd $PROJECT_NAME"
  echo "     # Add packages:  edit paket.dependencies + paket.references, then run: paket update"
  echo "     # Build with:    fun-build"
  echo "     # Run with:      dotnet run"
  echo "     # F# REPL:       replf"
  echo ""
  echo "Ionide + Paket + Fun.Build are fully integrated. Happy F# coding! 🎉"
  format_new_project "$PROJECT_NAME"
  add_to_root_slnx "$PROJECT_NAME/$PROJECT_NAME.fsproj"
  exit 0
fi

# ── Backend mode: scaffold an Oxpecker F# web project ────────────────────────
echo "🚀 Creating new F# web project: $PROJECT_NAME"

mkdir -p "$PROJECT_NAME"
cd "$PROJECT_NAME"

# 1. Create a clean F# console application
dotnet new console -lang F# --force

# 2. Switch to the Web SDK so ASP.NET Core is available
FSPROJ=$(ls *.fsproj)
sed -i 's|Sdk="Microsoft.NET.Sdk"|Sdk="Microsoft.NET.Sdk.Web"|' "$FSPROJ"
# Suppress NU1510: paket emits explicit PackageReferences for transitive deps, which .NET 10 flags
sed -i 's|<TargetFramework>|\n    <NoWarn>$(NoWarn);NU1510</NoWarn>\n    <TargetFramework>|' "$FSPROJ"

# 3. Create paket.dependencies with Oxpecker pinned to net10-compatible versions
cat > paket.dependencies << 'EOF'
source https://api.nuget.org/v3/index.json
source /usr/share/dotnet/sdk/$(dotnet --version)/FSharp/library-packs

storage: none

nuget FSharp.Core
nuget Oxpecker 1.3.0
nuget Oxpecker.ViewEngine 1.1.0
EOF

# 4. Create paket.references so Oxpecker is referenced in this project
# FSharp.Core is required because paket disables the implicit SDK reference
cat > paket.references << 'EOF'
FSharp.Core
Oxpecker
EOF

# 5. Install dependencies via paket (also wires up Paket.Restore.targets in the .fsproj)
paket install

# 6. Replace Program.fs with a minimal Oxpecker HTTP server
cat > Program.fs << EOF
open Microsoft.AspNetCore.Builder
open Microsoft.Extensions.DependencyInjection
open Oxpecker

let endpoints =
    [ route "/" <| text "Hello from $PROJECT_NAME!"
      route "/.well-known/appspecific/com.chrome.devtools.json" <| json {| |} ]

[<EntryPoint>]
let main args =
    let builder = WebApplication.CreateBuilder(args)
    builder.Services.AddRouting().AddOxpecker() |> ignore
    let app = builder.Build()
    app.UseRouting().UseOxpecker(endpoints) |> ignore
    app.Run()
    0
EOF

# 7. Create a minimal Fun.Build script (pure F#, no XML)
cat > build.fsx << 'EOF'
#r "nuget: Fun.Build"

open Fun.Build

pipeline "Build" {
    stage "Clean" {
        run "dotnet clean"
    }
    stage "Restore" {
        run "dotnet restore"
    }
    stage "Build" {
        run "dotnet build"
    }
    runIfOnlySpecified false
}

pipeline "Run" {
    stage "Run" {
        run "dotnet run"
    }
    runIfOnlySpecified true
}

pipeline "Watch" {
    stage "Watch" {
        run "dotnet watch run"
    }
    runIfOnlySpecified true
}

tryPrintPipelineCommandHelp ()
EOF

echo ""
echo "✅ Project '$PROJECT_NAME' created successfully!"
echo ""
echo "   Next steps:"
echo "     cd $PROJECT_NAME"
echo "     # Add packages:  edit paket.dependencies + paket.references, then run: paket update"
echo "     # Build with:    fun-build"
echo "     # Run with:      dotnet run"
echo ""
echo "Ionide + Paket + Oxpecker + Fun.Build are fully integrated. Happy F# coding! 🎉"
format_new_project "$PROJECT_NAME"
add_to_root_slnx "$PROJECT_NAME/$PROJECT_NAME.fsproj"
